### ISSUE TITLE
Replacing mappers for same error type

### ISSUE THREAD

**Issue by tpluscode** [PDMLab/http-problem-details-mapper#21]
Right now the mapper registry is a plain array. Because of that, adding a second mapper for an error already registered is impossible.

I propose to refactor the registry so that any pre-existing mapper was replaced instead.

**Comment by tpluscode** [comment]
Ok, I see that this is by design, so maybe an opt-in parameter should control that?

**Comment by AlexZeitler** [comment]
Out of curiosity: when does this scenario happen aside from „accidentally”? Do you do dynamic registration?

**Comment by tpluscode** [comment]
I built a reusable API middleware which registers some default mappers and adds the problem+json middleware to its router.

Now I wanted to add custom handler in a final application, which would replace some defaults
